#!/bin/bash

# Array of processes
processes=(
    "vpn"
    "sp"
    "tls"
)

# Loop through each process and spawn an Alacritty instance
for process in "${processes[@]}"; do
    alacritty --class=Alacritty_$process --command bash -ci '$process; exec bash'
    sleep 0.5
done
