#!/usr/bin/env bash

if [[ -n "${SPACE}" ]]; then
  echo "Work space detected"
  FILE=".tmux.conf.work"
else
  echo "Generic space detected"
  FILE=".tmux.conf"
fi

ln -sf $(pwd)/$FILE ~/.tmux.conf
echo 'Done'
