#!/usr/bin/env bash

if [[ -n "${SPACE}" ]]; then
  echo "Work space detected"
  FILE=".bashrc.work"
else
  echo "Generic space detected"
  FILE=".bashrc"
fi

ln -sf $(pwd)/$FILE ~/.bashrc
echo "Done"

